/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BaseDeDatos.ConsultasSQLTablaArticulo;
import baseDatos.ConexionBaseDatos;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Articulo;

/**
 *
 * @author Fabricio
 */
public class FrmBuscarArticulo extends javax.swing.JDialog {
    private boolean aceptar;
    ConexionBaseDatos conexion;
    Articulo oArticulo;
    ArrayList articulos;
    private int fila;
    private String[][] datos;
    /**
     * Creates new form frmBuscarArticulo
     */
    public FrmBuscarArticulo(java.awt.Frame parent, boolean modal, ConexionBaseDatos pConexion) {
        super(parent, modal);
        initComponents();
        this.setMinimumSize(new Dimension(660, 541));  // Impide hacer más pequeño el frame
        this.setLocationRelativeTo(parent);
        this.aceptar = false;
        this.conexion = pConexion;
        this.datos = new String[0][5];
        this.cargarDatosArticulos();
    }
    /**
     * El que asigna los datos al panel en el frame según los datos(matriz) y su cabecera(arreglo)
     */
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    /**
     * Cabecera del Panel correspondiente a la tabla Dueño
     * @return un arreglo con la cabecera correspondiente a cada tabla de la base de datos
     */
    
    private String[] cabecerasArticulo = {"Código", "Descripción", "Costo", "Ganancia", "Precio Venta"};
    
    /**
     * Redimensiona el Panel según los datos de la tabla
     */
    private void redimensionarMatriz() {
        String[][] respaldo = this.datos;   // Respalda los datos de la matriz principal en una auxiliar

        this.datos = new String[respaldo.length + 1][5]; // Inicializa la matriz sumandole un fila adicional, con la cantidad de columnas asginadas por parámetros
        
        // Permite redimensionar la matrix con los datos de la matrix auxiliar más la columna nueva sin datos
        for (int i = 0; i < respaldo.length; i++) {
            for (int j = 0; j < respaldo[0].length; j++) {
                this.datos[i][j] = respaldo[i][j];  // Vuelve agregar los datos de la matrix auxiliar para no perder ningúna datos
            }
        }
    }
    
    public boolean isAceptar(){
        return this.aceptar;
    }
    
    public Articulo getArticulo(){
        double costo = Double.parseDouble(this.datos[fila][2]);
        double porcentaje = Double.parseDouble(this.datos[fila][3]);
        double precio_venta = Double.parseDouble(this.datos[fila][4]);
        return oArticulo;
    }
    
    public void cargarDatosArticulos(){
        ConsultasSQLTablaArticulo oA = new ConsultasSQLTablaArticulo(conexion);
        articulos = oA.obtenerArticulo();
        if(!oA.isError()){
            if(articulos.size()>0){
                for(int i = 0; i < articulos.size(); i++){
                    Articulo oArt = (Articulo)articulos.get(i);
                    this.redimensionarMatriz();
                    this.datos[this.datos.length - 1][0] = oArt.getCodigo_articulo();
                    this.datos[this.datos.length - 1][1] = oArt.getDescripcion();
                }
                this.modelo.setDataVector(datos, cabecerasArticulo); // Se prepara el panel con los datos y cabecera determinados
                this.panel.setModel(modelo);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error inesperado");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUSCAR ARTÍCULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 0);

        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(panel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 580, 238);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel2.setText("Filtrar por nombre: ");

        jTextField1.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N

        jButton1.setText("Filtrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 640, 0);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(350, 460, 110, 35);

        btnModificar.setText("Seleccionar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(170, 460, 110, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            if(this.panel.getSelectedRow() >=0){
                fila = this.panel.getSelectedRow();
                this.setVisible(false);
                aceptar = true;
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar al menos una fila");
            }
        }
    }//GEN-LAST:event_panelMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(this.panel.getSelectedRow() >=0){
            fila = this.panel.getSelectedRow();
            this.setVisible(false);
            aceptar = true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar al menos una fila");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable panel;
    // End of variables declaration//GEN-END:variables
}
