/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BaseDeDatos.ConsultasSQLTablaProveedor;
import baseDatos.ConexionBaseDatos;
import java.awt.Dimension;
import java.util.ArrayList;
import javafx.scene.control.ButtonBar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Proveedor;

/**
 *
 * @author Fabricio
 */
public class FrmCXP extends javax.swing.JDialog {
    private ConexionBaseDatos conexion;
    private String[][] datos;
    private ArrayList personas;
    /**
     * Creates new form FrmCXP
     */
    public FrmCXP(java.awt.Frame parent, boolean modal, ConexionBaseDatos pConexion) {
        super(parent, modal);
        initComponents();
        this.setMinimumSize(new Dimension(877, 644));
        this.setLocationRelativeTo(null);
        this.conexion = pConexion;
        this.personas = new ArrayList();
        this.datos = new String[0][7];
        this.redimensionarMatriz();
        this.cargarTablaProveedores();
    }
    /**
     * El que asigna los datos al panel en el frame según los datos(matriz) y su cabecera(arreglo)
     */
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private String[] cabeceraProveedor = {"CÉDULA", "RAZÓN SOCIAL", "TELÉFONO 1", "TELÉFONO 2", "CORREO ELECTRÓNICO", "DIRECCIÓN", "PLAZO CRÉDITO(DÍAS)"};
    
    public void redimensionarMatriz(){
        String[][] respaldo = this.datos;   // Respalda los datos de la matriz principal en una auxiliar

        this.datos = new String[respaldo.length + 1][7]; // Inicializa la matriz sumandole un fila adicional, con la cantidad de columnas asginadas por parámetros
        
        // Permite redimensionar la matrix con los datos de la matrix auxiliar más la columna nueva sin datos
        for (int i = 0; i < respaldo.length; i++) {
            for (int j = 0; j < respaldo[0].length; j++) {
                this.datos[i][j] = respaldo[i][j];  // Vuelve agregar los datos de la matrix auxiliar para no perder ningúna datos
            }
        }
    }
    public void cargarTablaProveedores(){
        ConsultasSQLTablaProveedor oC = new ConsultasSQLTablaProveedor(conexion);
        personas = oC.obtenerProveedor();
        if(!oC.isError()){
            if(personas.size() > 0){
                for(int i = 0; i<personas.size(); i++){
                    Proveedor aux = (Proveedor)personas.get(i);
                    this.datos = new String[0][7];
                    this.redimensionarMatriz();
                    try{
                        this.datos[this.datos.length - 1][0] = aux.getCedula();
                        this.datos[this.datos.length - 1][1] = aux.getRazon_social();
                        this.datos[this.datos.length - 1][2] = aux.getTelefono1();
                        this.datos[this.datos.length - 1][3] = aux.getTelefono2();
                        this.datos[this.datos.length - 1][4] = aux.getCorreo();
                        this.datos[this.datos.length - 1][5] = aux.getDireccion();
                        this.datos[this.datos.length - 1][6] = aux.getDias_credito();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane, e);
                    }
                }
                this.modelo.setDataVector(datos, cabeceraProveedor); // Se prepara el panel con los datos y cabecera determinados
                this.panel.setModel(modelo);  
            }else{
                this.limpiarMatriz();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, oC.getErrorMsg());
        }
    }
    
    public void limpiarMatriz(){
        this.redimensionarMatriz();
        this.modelo.setDataVector(null, cabeceraProveedor); // Se prepara el panel con los datos y cabecera determinados
        this.panel.setModel(modelo);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarProveedor = new javax.swing.JButton();
        btnNuevoProveedor = new javax.swing.JButton();
        btnModificarProveedor = new javax.swing.JButton();
        btnAbonarFactura = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnNuevoProveedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnModificarProveedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnEliminarProveedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUENTAS POR PAGAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 80);

        jScrollPane1.setViewportView(panel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 810, 310);

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Solufak Software S.A. | Versión 1.0.0.0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 550, 870, 14);

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FACTURAS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 420, 210, 14);

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PROVEEDOR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 420, 470, 15);

        btnEliminarProveedor.setText("Eliminar");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarProveedor);
        btnEliminarProveedor.setBounds(350, 470, 140, 40);

        btnNuevoProveedor.setText("Nuevo");
        btnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoProveedor);
        btnNuevoProveedor.setBounds(30, 470, 140, 40);

        btnModificarProveedor.setText("Modificar");
        btnModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarProveedor);
        btnModificarProveedor.setBounds(190, 470, 140, 40);

        btnAbonarFactura.setText("Abonar");
        btnAbonarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbonarFactura);
        btnAbonarFactura.setBounds(670, 470, 140, 40);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(640, 440, 200, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(30, 442, 470, 10);

        jMenu1.setText("Archivo");

        jMenuItem6.setText("Salir");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Proveedores");

        mnNuevoProveedor.setText("Nuevo proveedor");
        mnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNuevoProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(mnNuevoProveedor);
        jMenu2.add(jSeparator1);

        mnModificarProveedor.setText("Modificar proveedor");
        mnModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnModificarProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(mnModificarProveedor);
        jMenu2.add(jSeparator2);

        mnEliminarProveedor.setText("Eliminar proveedor");
        mnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(mnEliminarProveedor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Facturas");

        jMenuItem1.setText("Ver Facturas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator3);

        jMenuItem2.setText("Nuevo abono");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedorActionPerformed
        // TODO add your handling code here:
        frmInsertarOModificarProveedor oM = new frmInsertarOModificarProveedor(null, true);
        oM.setVisible(true);
        if(oM.isAceptar()){
            ConsultasSQLTablaProveedor cP = new ConsultasSQLTablaProveedor(conexion);
            cP.agregarProveedor(oM.getProveedor());
            if(!cP.isError()){
                JOptionPane.showMessageDialog(rootPane, "Registro agregado correctamente");
                this.cargarTablaProveedores();
            }else{
                JOptionPane.showMessageDialog(rootPane, cP.getErrorMsg());
            }
        }
    }//GEN-LAST:event_btnNuevoProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        // TODO add your handling code here:
        int fila = this.panel.getSelectedRow(); 
        if(fila >= 0){
            String cedula = this.datos[fila][0];
            ConsultasSQLTablaProveedor oCP = new ConsultasSQLTablaProveedor(conexion);
            oCP.borrarDatos(cedula);
            if(!oCP.isError()){
                JOptionPane.showMessageDialog(rootPane, "Registro eliminaro correctamente");
                this.cargarTablaProveedores();
            }else{
                JOptionPane.showMessageDialog(rootPane, oCP.getErrorMsg());
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe de seleccionar al menos una fila");
        }
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProveedorActionPerformed
        // TODO add your handling code here:
        int fila = this.panel.getSelectedRow(); 
        if(this.panel.getSelectedRow() >= 0){
            
            Proveedor aux = (Proveedor)personas.get(fila);
            frmInsertarOModificarProveedor fIM = new frmInsertarOModificarProveedor(null, true, aux);
            fIM.setVisible(true);
            if(fIM.isAceptar()){
                ConsultasSQLTablaProveedor oCP = new ConsultasSQLTablaProveedor(conexion);
                oCP.actualizarProveedor(fIM.getProveedor(), aux.getCedula());
                if(!oCP.isError()){
                JOptionPane.showMessageDialog(rootPane, "Registro modificado correctamente");
                this.cargarTablaProveedores();
            }else{
                JOptionPane.showMessageDialog(rootPane, oCP.getErrorMsg());
            }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe de seleccionar al menos una fila");
        }
    }//GEN-LAST:event_btnModificarProveedorActionPerformed

    private void btnAbonarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbonarFacturaActionPerformed

    private void mnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNuevoProveedorActionPerformed
        // TODO add your handling code here:
        this.btnNuevoProveedorActionPerformed(evt);
    }//GEN-LAST:event_mnNuevoProveedorActionPerformed

    private void mnModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnModificarProveedorActionPerformed
        // TODO add your handling code here:
        this.btnModificarProveedorActionPerformed(evt);
    }//GEN-LAST:event_mnModificarProveedorActionPerformed

    private void mnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarProveedorActionPerformed
        // TODO add your handling code here:
        this.btnEliminarProveedorActionPerformed(evt);
    }//GEN-LAST:event_mnEliminarProveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonarFactura;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnModificarProveedor;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JMenuItem mnEliminarProveedor;
    private javax.swing.JMenuItem mnModificarProveedor;
    private javax.swing.JMenuItem mnNuevoProveedor;
    private javax.swing.JTable panel;
    // End of variables declaration//GEN-END:variables
}
