/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BaseDeDatos.ConsultasSQLTablaArticulo;
import BaseDeDatos.ConsultasSQLTablaClienteContado;
import baseDatos.ConexionBaseDatos;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Articulo;
import logica.ClienteContado;
import logica.ClienteCredito;
import logica.Facturacion;

/**
 *
 * @author Fabricio
 */
public class FrmFacturacion extends javax.swing.JDialog {
    private boolean compra;
    private String[][] datos = new String[0][7];                  // Permite conocer los campos que tendrá el panel según la tabla seleccionada
    private double impuestoVentas = 0.13;
    private boolean continuar = false;
    ConexionBaseDatos conexion;
    Articulo oArticulo;
    ClienteContado oCliente;
    Facturacion oFactura;
    
    /**
     * Creates new form frmPanelVenta
     */
    public FrmFacturacion(java.awt.Frame parent, boolean modal, ConexionBaseDatos pConexion) {
        super(parent, modal);
        initComponents();
        this.setMinimumSize(new Dimension(931, 731));  // Impide hacer más pequeño el frame
        this.setLocationRelativeTo(parent);
        this.txtIV.setText("13%");
        oFactura = new Facturacion();
        oCliente = null;
        this.conexion = pConexion;
        this.inicializarPanel();
        this.calcularFechaActual();
    }
    
    public boolean isCompra(){
        return this.compra;
    }
    /**
     * El que asigna los datos al panel en el frame según los datos(matriz) y su cabecera(arreglo)
     */
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    /**
     * Cabecera del Panel correspondiente a la tabla Dueño
     * @return un arreglo con la cabecera correspondiente a cada tabla de la base de datos
     */
    
    private String[] cabecerasVenta = {"Cantidad", "Código", "Descripción", "Subtotal",
        "Descuento", "Impuesto Venta", "Total"};
    
    /**
     * Redimensiona el Panel según los datos de la tabla
     */
    private void redimensionarMatriz() {
        String[][] respaldo = this.datos;   // Respalda los datos de la matriz principal en una auxiliar

        this.datos = new String[respaldo.length + 1][7]; // Inicializa la matriz sumandole un fila adicional, con la cantidad de columnas asginadas por parámetros
        
        // Permite redimensionar la matrix con los datos de la matrix auxiliar más la columna nueva sin datos
        for (int i = 0; i < respaldo.length; i++) {
            for (int j = 0; j < respaldo[0].length; j++) {
                this.datos[i][j] = respaldo[i][j];  // Vuelve agregar los datos de la matrix auxiliar para no perder ningúna datos
            }
        }
    }
    
    public void inicializarPanel(){
        this.modelo.setDataVector(datos, cabecerasVenta); // Se prepara el panel con los datos y cabecera determinados
        this.panelDeDatos.setModel(modelo); 
        this.cbxTipoFactura.requestFocus();
    }
    
    public void calcularFechaActual(){
        Date fecha = new Date();
        this.cpFecha.setText(fecha.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelDeDatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnBorrarArticulo = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtIV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JButton();
        cpTotalFacturaGeneral = new javax.swing.JFormattedTextField();
        cpImpuestoFacturaGeneral = new javax.swing.JFormattedTextField();
        cpDescuentoFacturaGeneral = new javax.swing.JFormattedTextField();
        cpSubtotalFacturaGeneral = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        cpFecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxTipoFactura = new javax.swing.JComboBox();
        txtTotal = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panelDeDatos.setBackground(new java.awt.Color(153, 0, 0));
        panelDeDatos.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        panelDeDatos.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(panelDeDatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 452, 363);

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel3.setText("Código Artículo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 90, 15);

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel4.setText("Descripción");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 90, 170, 14);

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel5.setText("Subtotal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 90, 80, 15);

        jLabel6.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel6.setText("Desc %");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 90, 60, 15);

        jLabel7.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel7.setText("I.V.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 90, 40, 15);

        jLabel8.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel8.setText("Total");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(590, 90, 60, 15);

        txtCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(710, 110, 50, 25);

        btnAgregar.setFont(new java.awt.Font("Raleway", 1, 10)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-insertar.png"))); // NOI18N
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(780, 90, 50, 50);

        btnBorrarArticulo.setFont(new java.awt.Font("Raleway", 1, 10)); // NOI18N
        btnBorrarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-eliminar.png"))); // NOI18N
        btnBorrarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarArticuloActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrarArticulo);
        btnBorrarArticulo.setBounds(850, 90, 50, 50);

        txtCodigo.setEnabled(false);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(10, 110, 90, 25);

        txtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDescripcion.setFocusable(false);
        txtDescripcion.setRequestFocusEnabled(false);
        txtDescripcion.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(109, 110, 210, 25);

        txtSubtotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtSubtotal.setFocusable(false);
        txtSubtotal.setRequestFocusEnabled(false);
        txtSubtotal.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(txtSubtotal);
        txtSubtotal.setBounds(330, 110, 108, 25);

        txtIV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtIV.setFocusable(false);
        txtIV.setRequestFocusEnabled(false);
        txtIV.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(txtIV);
        txtIV.setBounds(520, 110, 62, 25);

        jLabel9.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel9.setText("Cantidad");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(710, 90, 60, 15);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel10.setText("Subtotal:");

        jLabel11.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel11.setText("Descuento:");

        jLabel12.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel12.setText("Impuesto Ventas:");

        jLabel13.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jLabel13.setText("Total:");

        btnFacturar.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        btnFacturar.setText("FACTURAR");
        btnFacturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        cpTotalFacturaGeneral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cpTotalFacturaGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cpTotalFacturaGeneral.setFocusable(false);
        cpTotalFacturaGeneral.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        cpTotalFacturaGeneral.setRequestFocusEnabled(false);
        cpTotalFacturaGeneral.setVerifyInputWhenFocusTarget(false);

        cpImpuestoFacturaGeneral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cpImpuestoFacturaGeneral.setFocusable(false);
        cpImpuestoFacturaGeneral.setRequestFocusEnabled(false);
        cpImpuestoFacturaGeneral.setVerifyInputWhenFocusTarget(false);

        cpDescuentoFacturaGeneral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cpDescuentoFacturaGeneral.setFocusable(false);
        cpDescuentoFacturaGeneral.setRequestFocusEnabled(false);
        cpDescuentoFacturaGeneral.setVerifyInputWhenFocusTarget(false);

        cpSubtotalFacturaGeneral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cpSubtotalFacturaGeneral.setFocusable(false);
        cpSubtotalFacturaGeneral.setRequestFocusEnabled(false);
        cpSubtotalFacturaGeneral.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cpTotalFacturaGeneral)
                    .addComponent(cpImpuestoFacturaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(cpDescuentoFacturaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(cpSubtotalFacturaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cpSubtotalFacturaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cpDescuentoFacturaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cpImpuestoFacturaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cpTotalFacturaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(480, 150, 420, 363);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        cpFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cpFecha.setFocusable(false);
        cpFecha.setRequestFocusEnabled(false);
        cpFecha.setVerifyInputWhenFocusTarget(false);

        jLabel14.setFont(new java.awt.Font("Poiret One", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha:");

        txtCodigoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoClienteKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poiret One", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código Cliente:");

        jLabel1.setFont(new java.awt.Font("Poiret One", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo Factura:");

        cbxTipoFactura.setFont(new java.awt.Font("Poiret One", 1, 12)); // NOI18N
        cbxTipoFactura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contado", "Crédito" }));
        cbxTipoFactura.setToolTipText("Tipo de Cliente");
        cbxTipoFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxTipoFacturaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(cbxTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 920, 60);

        txtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.00"))));
        getContentPane().add(txtTotal);
        txtTotal.setBounds(590, 110, 110, 25);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Buscar Cliente: F2");

        jLabel16.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Buscar Artículo: F1");

        jLabel17.setFont(new java.awt.Font("Raleway", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Solufak Software S.A | Versión 1.0.0.0");

        jLabel18.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Accesos Directos");

        jLabel19.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Nuevo Artículo: F3");

        jLabel20.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Nuevo Cliente: F4");

        jLabel21.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Ir a Invetarios: F5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel21))
                            .addComponent(jLabel20))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(90, 520, 710, 120);

        txtDescuento.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        getContentPane().add(txtDescuento);
        txtDescuento.setBounds(450, 110, 50, 25);

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimientos");

        jMenuItem1.setText("Impuesto Ventas");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Seguridad");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void limpiarBarra(){
        this.txtCodigo.setText("");
        this.txtDescripcion.setText("");
        this.txtSubtotal.setText("");
        this.txtTotal.setText("");
        this.txtDescuento.getModel().setValue(0);
        this.txtCantidad.getModel().setValue(0);
    }
    
    public void sumarFactura(Articulo pArticulo){
        
        oFactura.agregarArticulo(pArticulo);
        this.cpSubtotalFacturaGeneral.setText(String.valueOf(oFactura.calcularSubtotal()));
        this.cpDescuentoFacturaGeneral.setText(String.valueOf(oFactura.calcularDescuento()));
        this.cpImpuestoFacturaGeneral.setText(String.valueOf(oFactura.calculoImpuestoVentas()));
        this.cpTotalFacturaGeneral.setText(String.valueOf(oFactura.calcularTotal()));
    }
    
    public void restarFactura(){
        boolean continuar = false;
        int i = 0;
        int j = 0;
        int o = 0;
        int h = 0;
        int fila = this.panelDeDatos.getSelectedRow();
        String codigoEliminar = this.datos[fila][1];
        oFactura.restarDatos(codigoEliminar, fila);
        this.datos[fila][0] = "";
        this.datos[fila][1] = "";
        this.datos[fila][2] = "";
        this.datos[fila][3] = "";
        this.datos[fila][4] = "";
        this.datos[fila][5] = "";
        this.datos[fila][6] = "";
        
        int filaDatos = this.datos.length;
        String[][] aux = new String[filaDatos-1][7];
        
        do{
            do{
                if(!this.datos[i][j].equals("")){
                    aux[o][h] = this.datos[i][j];
                    h++;
                    continuar = true;
                }
                j++;
            }while(j<this.datos[i].length);
            if(continuar){
                h=0;
                o++;
            }
            continuar = false;
            j=0;
            i++;
        }while(i < this.datos.length);
            
        
        this.datos = aux;
        this.modelo.setDataVector(datos, cabecerasVenta); // Se prepara el panel con los datos y cabecera determinados
        this.panelDeDatos.setModel(modelo);
        this.cpSubtotalFacturaGeneral.setText(String.valueOf(oFactura.calcularSubtotal()));
        this.cpDescuentoFacturaGeneral.setText(String.valueOf(oFactura.calcularDescuento()));
        this.cpImpuestoFacturaGeneral.setText(String.valueOf(oFactura.calculoImpuestoVentas()));
        this.cpTotalFacturaGeneral.setText(String.valueOf(oFactura.calcularTotal()));
        
    }
    
    public void calculoTotal(){
        DecimalFormat decimales = new DecimalFormat("0.00");
        String codigo = this.txtCodigo.getText();
        String descripcion = this.txtDescripcion.getText();
        int cantidad = Integer.parseInt(this.txtCantidad.getModel().getValue().toString());
        double subtotal = Double.parseDouble(this.txtSubtotal.getText()) * cantidad;
        double descuento = subtotal * (Double.parseDouble(this.txtDescuento.getModel().getValue().toString())/100);
        double impuesto = (subtotal-descuento) * this.impuestoVentas;
        double total = (subtotal-descuento)+impuesto;
        
//        Articulo nA = new Articulo(cantidad, codigo, descripcion, subtotal, descuento, impuesto, total);
        
        if(!this.txtCodigo.getText().equals("") || !this.txtDescripcion.getText().equals("") || 
            !this.txtSubtotal.getText().equals("") || !this.txtTotal.getText().equals("")){
            
            this.redimensionarMatriz();        
            this.datos[this.datos.length - 1][0] = String.valueOf(cantidad);
            this.datos[this.datos.length - 1][1] = codigo;
            this.datos[this.datos.length - 1][2] = descripcion;
            this.datos[this.datos.length - 1][3] = String.valueOf(subtotal);
            this.datos[this.datos.length - 1][4] = String.valueOf(descuento);
            this.datos[this.datos.length - 1][5] = String.valueOf(impuesto);
            this.datos[this.datos.length - 1][6] = decimales.format(total);
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "Sucedió un error, vuelva a digitar todos los campos");
        }
        this.modelo.setDataVector(datos, cabecerasVenta); // Se prepara el panel con los datos y cabecera determinados
        this.panelDeDatos.setModel(modelo); 
//        this.sumarFactura(nA);
        this.limpiarBarra();
        this.txtCodigo.requestFocus(true);
        this.txtCodigo.requestFocus();
        this.txtCantidad.getModel().setValue(1);
    }
    
    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturarActionPerformed
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(this.txtCantidad.getModel().getValue().toString());
        if(numero >= 1){
            this.calculoTotal();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe de agregar al menos una cantidad");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    public void calcularTotalBarra(){
        DecimalFormat decimales = new DecimalFormat("0.00");
        String dato = this.txtDescuento.getModel().getValue().toString(); 
        double descuento = Double.parseDouble(this.txtSubtotal.getText()) * Integer.parseInt(dato) / 100;
        double totalDescuento = Double.parseDouble(this.txtSubtotal.getText()) - descuento;
        double total = ( totalDescuento * (1 + this.impuestoVentas));
        this.txtTotal.setText(decimales.format(total));
    }
    
    public void BuscarArticulo(){
        FrmBuscarArticulo fB = new FrmBuscarArticulo(null, true, conexion);
        fB.setVisible(true);
        if(fB.isAceptar()){
            oArticulo = fB.getArticulo();
            this.txtCodigo.setText(oArticulo.getCodigo_articulo());
            this.txtDescripcion.setText(oArticulo.getDescripcion());
//            this.txtSubtotal.setText(String.valueOf(oArticulo.getPrecio_venta()));
            this.calcularTotalBarra();
            this.txtDescuento.requestFocus();
            this.txtCodigo.requestFocus(false);
            continuar = true;
        }
    }
    public void BuscarCliente(){
        FrmBuscarCliente fB = new FrmBuscarCliente(null, true, conexion);
        fB.setVisible(true);
        if(fB.isAceptar()){
            if(this.cbxTipoFactura.getSelectedItem().toString().equals("Crédito") && !fB.isClienteCredito()){
                JOptionPane.showMessageDialog(rootPane, "No se permite facturar a crédito");
                this.txtCodigo.setText("");
                this.cbxTipoFactura.requestFocus();
            }else{
                if(fB.isClienteCredito()){
                    ClienteCredito aux = (ClienteCredito)fB.getCliente().get(0);
                    this.txtCodigoCliente.setText(aux.getCodigo());
                    this.txtCodigo.setEnabled(true);
                    this.txtCodigo.requestFocus();
                    continuar = true;
                }else{
                    ClienteContado aux = (ClienteContado)fB.getCliente().get(0);
                    this.txtCodigoCliente.setText(aux.getCodigo());
                    this.txtCodigo.setEnabled(true);
                    this.txtCodigo.requestFocus();
                    continuar = true;
                }
            }
            
        }
    }
    
    public void LlamarCliente(){
        boolean seleccion = false;
        if(!continuar){
            ConsultasSQLTablaClienteContado oC = new ConsultasSQLTablaClienteContado(conexion);
            ArrayList cliente = oC.obtenerClienteContado();
            if(oC.isError()){
                for(int i=0; i<cliente.size(); i++){
                    ClienteContado aux = (ClienteContado)cliente.get(i);
                    if(aux.getCodigo().equals(this.txtCodigoCliente)){
                        oCliente = aux;
                        this.txtCodigo.requestFocus();
                        continuar = false;
                        break;
                    }else{
                        continuar = true;
                    }
                }
                if(seleccion){
                    JOptionPane.showMessageDialog(rootPane, "Este cliente no existe");
                }
            }
        }
    }
    
    public void LlamarArticuloBarra(){
        boolean seleccion = false;
        if(!continuar){
            ConsultasSQLTablaArticulo oC  = new ConsultasSQLTablaArticulo(conexion);
            ArrayList articulo = oC.obtenerArticulo();
            for(int i = 0; i<articulo.size(); i++){
                Articulo oArt = (Articulo)articulo.get(i);
                if(oArt.getCodigo_articulo().equals(this.txtCodigo.getText())){
                    oArticulo = oArt;
                    this.txtCodigo.setText(oArticulo.getCodigo_articulo());
                    this.txtDescripcion.setText(oArticulo.getDescripcion());
//                    this.txtSubtotal.setText(String.valueOf(oArticulo.getPrecio_venta()));
                    this.calcularTotalBarra();
                    this.txtDescuento.requestFocus();
                    continuar = false;
                    break;
                }else{
                    continuar = true;
                }
            }
            if(seleccion){
                JOptionPane.showMessageDialog(rootPane, "Este artículo no existe");
                this.txtCodigo.setText("");
                this.txtDescripcion.setText("");
                this.txtSubtotal.setText("");
                this.txtDescuento.getModel().setValue(0);
                this.txtTotal.setText("");
                this.txtCodigo.requestFocus();
            }
        }else{
            if(!this.txtCodigo.getText().equals("")){
                this.txtDescripcion.setText(oArticulo.getDescripcion());
//                this.txtSubtotal.setText(String.valueOf(oArticulo.getPrecio_venta()));
                this.calcularTotalBarra();
                this.txtDescuento.requestFocus();
                continuar = false;
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe digitar el código, o presiona F1 para buscar");
                
            }
        }
    }
    
    private void txtCodigoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1){ 
            this.BuscarArticulo();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_F2){ 
            this.BuscarCliente();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){ 
            this.BuscarCliente();
        }
        if(evt.getKeyCode() == KeyEvent.VK_TAB){ 
            this.txtCodigo.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoClienteKeyPressed

    private void btnBorrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarArticuloActionPerformed
        // TODO add your handling code here:
        if(this.datos.length>0){                                 // Valida que hayan datos en el table
                int fila = this.panelDeDatos.getSelectedRow();            // Obtiene la fila seleccionada
                if(fila >=0){                                        // Valida que haya una fila selecciona
                    
                    int respuesta = JOptionPane.showConfirmDialog(this, 
                           "¿Está seguro de borrar el registro?", "Borrar", JOptionPane.YES_NO_OPTION); // Muestra un mensaje de alerta
                    // En caso de presionar Si
                    if ( respuesta == JOptionPane.YES_OPTION ) { 
                        try{
                            this.restarFactura();
                            JOptionPane.showMessageDialog(rootPane, "Registro borrado exitosamente");
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(rootPane, "Ha sucedido un error, no se borró la fila");
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Debe de seleccionar la fila que desea eliminar");
                }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Acción inválida, no hay datos en el panel");
        }
    }//GEN-LAST:event_btnBorrarArticuloActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1){ 
            this.BuscarArticulo();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_F2){ 
            this.BuscarCliente();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){ 
            this.LlamarArticuloBarra();
            this.txtCantidad.requestFocus();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_TAB){ 
            this.txtCantidad.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void cbxTipoFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxTipoFacturaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_TAB){ 
            this.txtCodigoCliente.requestFocus();
        }
    }//GEN-LAST:event_cbxTipoFacturaKeyPressed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrarArticulo;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JComboBox cbxTipoFactura;
    private javax.swing.JFormattedTextField cpDescuentoFacturaGeneral;
    private javax.swing.JTextField cpFecha;
    private javax.swing.JFormattedTextField cpImpuestoFacturaGeneral;
    private javax.swing.JFormattedTextField cpSubtotalFacturaGeneral;
    private javax.swing.JFormattedTextField cpTotalFacturaGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable panelDeDatos;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JSpinner txtDescuento;
    private javax.swing.JTextField txtIV;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JFormattedTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
