/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import baseDatos.ConexionBaseDatos;
import java.awt.Dimension;

/**
 *
 * @author Fabricio
 */
public class FrmPanelPrincipal extends javax.swing.JFrame {
    private String accion;
    ConexionBaseDatos conexion;
    
    /**
     * Creates new form frmPanelPrincipal
     */
    public FrmPanelPrincipal(ConexionBaseDatos pConexion) {
        initComponents();
        this.setMinimumSize(new Dimension(883, 549));  // Impide hacer más pequeño el frame
        this.setLocationRelativeTo(null);
        accion = "";
        this.conexion = pConexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFacturacion = new javax.swing.JButton();
        btnCXP = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnRecursoHumano = new javax.swing.JButton();
        btnParametros = new javax.swing.JButton();
        btnCXC = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Poiret One", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-logo.png"))); // NOI18N
        jLabel1.setText("Solufak Software");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 90);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnFacturacion.setFont(new java.awt.Font("Poiret One", 1, 14)); // NOI18N
        btnFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-facturacion.png"))); // NOI18N
        btnFacturacion.setToolTipText("Facturación");
        btnFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });

        btnCXP.setFont(new java.awt.Font("Poiret One", 1, 14)); // NOI18N
        btnCXP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-cxp.png"))); // NOI18N
        btnCXP.setToolTipText("Artículos");
        btnCXP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCXPActionPerformed(evt);
            }
        });

        btnInventario.setFont(new java.awt.Font("Poiret One", 1, 14)); // NOI18N
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-inventario.png"))); // NOI18N
        btnInventario.setToolTipText("Inventario");
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnRecursoHumano.setFont(new java.awt.Font("Poiret One", 1, 14)); // NOI18N
        btnRecursoHumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-recurso-humano.png"))); // NOI18N
        btnRecursoHumano.setToolTipText("Artículos");
        btnRecursoHumano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecursoHumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursoHumanoActionPerformed(evt);
            }
        });

        btnParametros.setFont(new java.awt.Font("Poiret One", 1, 14)); // NOI18N
        btnParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-parametros.png"))); // NOI18N
        btnParametros.setToolTipText("Inventario");
        btnParametros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParametrosActionPerformed(evt);
            }
        });

        btnCXC.setFont(new java.awt.Font("Poiret One", 1, 14)); // NOI18N
        btnCXC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-cxc.png"))); // NOI18N
        btnCXC.setToolTipText("Cliente");
        btnCXC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCXC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCXCActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/icono-salir.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCXP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCXC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(btnRecursoHumano, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecursoHumano, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCXC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCXP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 120, 820, 350);

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Solufak Software Version 1.0.0.0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 500, 880, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCXCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCXCActionPerformed
        // TODO add your handling code here:
        FrmCXC oA = new FrmCXC(this, true, conexion);
        oA.setVisible(true);
    }//GEN-LAST:event_btnCXCActionPerformed

    private void btnCXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCXPActionPerformed
        // TODO add your handling code here:
        FrmCXP oCXP = new FrmCXP(this, true, conexion);
        oCXP.setVisible(true);
    }//GEN-LAST:event_btnCXPActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        // TODO add your handling code here:
        FrmFacturacion oPV = new FrmFacturacion(this, true, conexion);
        oPV.setVisible(true);
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        FrmInventario oI = new FrmInventario(this, true, conexion);
        oI.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRecursoHumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursoHumanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecursoHumanoActionPerformed

    private void btnParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParametrosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCXC;
    private javax.swing.JButton btnCXP;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnParametros;
    private javax.swing.JButton btnRecursoHumano;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
